### ISSUE TITLE
Install issue: Some packages not included in package.json

### ISSUE THREAD

**Issue by soos3d** [a6b8/evmNodes#10]
It looks like those 2 packages are not included in `package.json`. I was getting `'module not found'` errors when starting the CLI.

```
    "figlet": "^1.7.0",
    "inquirer": "^9.2.13",
```

I had to install them separately with`npm i figlet inquirer` and then it worked.

**Comment by a6b8** [comment]
Thank you for bringing this to attention. The issue has been addressed/fixed
